default:
  log_level: INFO
  max_agents: 10

development:
  neo4j_uri: "bolt://localhost:7687"
  neo4j_user: "neo4j"
  neo4j_password: "dev_password"

production:
  neo4j_uri: "bolt://neo4j-prod-server:7687"
  neo4j_user: "neo4j"
  neo4j_password: "prod_password"

testing:
  neo4j_uri: "bolt://localhost:7687"
  neo4j_user: "neo4j"
  neo4j_password: "test_password"