default:
  log_level: INFO
  max_agents: 10

development:
  database_url: "sqlite:///./dev.db"
  api_key: "dev_api_key"

production:
  database_url: "postgresql://user:password@localhost/prod_db"
  api_key: "prod_api_key"

testing:
  database_url: "sqlite:///./test.db"
  api_key: "test_api_key"